<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'nik' => 'EMP-001',
                'nama' => 'Budi Santoso',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1995-03-15',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_nikah' => 'Nikah',
                'golongan_darah' => 'A',
                'email' => 'budi.santoso@hris.com',
                'telepon' => '081234567890',
                'no_bpjs' => '1234567890123',
                'alamat' => 'Jl. Sudirman No. 123, Jakarta Selatan',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '12190',
                'divisi' => 'IT',
                'departemen' => 'Development',
                'jabatan' => 'Staff Developer',
                'grade' => 'Grade 3',
                'lokasi_kerja' => 'Kantor Pusat - Jakarta',
                'status_kepegawaian' => 'Tetap',
                'tanggal_masuk' => '2022-03-15',
                'tanggal_kontrak_habis' => null,
                'no_ktp' => '3175011503950001',
                'no_npwp' => '123456789012345',
                'no_kk' => '3175010101950001',
                'foto' => null,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'EMP-002',
                'nama' => 'Siti Rahayu',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1993-07-22',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'status_nikah' => 'Belum Nikah',
                'golongan_darah' => 'O',
                'email' => 'siti.rahayu@hris.com',
                'telepon' => '081234567891',
                'no_bpjs' => '1234567890124',
                'alamat' => 'Jl. Malioboro No. 45, Yogyakarta',
                'kota' => 'Yogyakarta',
                'provinsi' => 'DI Yogyakarta',
                'kode_pos' => '55211',
                'divisi' => 'HRD',
                'departemen' => 'HRGA',
                'jabatan' => 'HR Manager',
                'grade' => 'Grade 5',
                'lokasi_kerja' => 'Kantor Pusat - Jakarta',
                'status_kepegawaian' => 'Tetap',
                'tanggal_masuk' => '2021-01-10',
                'tanggal_kontrak_habis' => null,
                'no_ktp' => '3471012207930002',
                'no_npwp' => '123456789012346',
                'no_kk' => '3471010101930002',
                'foto' => null,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'EMP-003',
                'nama' => 'Andi Wijaya',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1997-11-08',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_nikah' => 'Belum Nikah',
                'golongan_darah' => 'B',
                'email' => 'andi.wijaya@hris.com',
                'telepon' => '081234567892',
                'no_bpjs' => '1234567890125',
                'alamat' => 'Jl. Asia Afrika No. 78, Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '40111',
                'divisi' => 'Finance',
                'departemen' => 'Accounting',
                'jabatan' => 'Staff Accounting',
                'grade' => 'Grade 2',
                'lokasi_kerja' => 'Kantor Cabang - Bandung',
                'status_kepegawaian' => 'Kontrak',
                'tanggal_masuk' => '2023-07-01',
                'tanggal_kontrak_habis' => '2024-06-30',
                'no_ktp' => '3273010811970003',
                'no_npwp' => '123456789012347',
                'no_kk' => '3273010101970003',
                'foto' => null,
                'status' => 'kontrak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'EMP-004',
                'nama' => 'Dewi Lestari',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1994-05-30',
                'jenis_kelamin' => 'P',
                'agama' => 'Hindu',
                'status_nikah' => 'Nikah',
                'golongan_darah' => 'AB',
                'email' => 'dewi.lestari@hris.com',
                'telepon' => '081234567893',
                'no_bpjs' => '1234567890126',
                'alamat' => 'Jl. Pemuda No. 100, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '60271',
                'divisi' => 'Marketing',
                'departemen' => 'Digital Marketing',
                'jabatan' => 'Marketing Manager',
                'grade' => 'Grade 4',
                'lokasi_kerja' => 'Kantor Pusat - Jakarta',
                'status_kepegawaian' => 'Tetap',
                'tanggal_masuk' => '2020-06-20',
                'tanggal_kontrak_habis' => null,
                'no_ktp' => '3578013005940004',
                'no_npwp' => '123456789012348',
                'no_kk' => '3578010101940004',
                'foto' => null,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 'EMP-005',
                'nama' => 'Rizky Pratama',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1998-01-12',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_nikah' => 'Belum Nikah',
                'golongan_darah' => 'O',
                'email' => 'rizky.pratama@hris.com',
                'telepon' => '081234567894',
                'no_bpjs' => '1234567890127',
                'alamat' => 'Jl. Pandanaran No. 55, Semarang',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '50132',
                'divisi' => 'IT',
                'departemen' => 'Network',
                'jabatan' => 'Staff Network',
                'grade' => 'Grade 2',
                'lokasi_kerja' => 'Kantor Pusat - Jakarta',
                'status_kepegawaian' => 'Tetap',
                'tanggal_masuk' => '2022-09-01',
                'tanggal_kontrak_habis' => null,
                'no_ktp' => '3374011201980005',
                'no_npwp' => '123456789012349',
                'no_kk' => '3374010101980005',
                'foto' => null,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::connection('pgsql')->table('pegawai')->insert($employees);
    }
}
